# Generated by Django 4.2.7 on 2023-11-24 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_alter_book_created_at_alter_category_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Category',
            new_name='category',
        ),
    ]
